### PR TITLE
Added Arkanoid III SNES game support

### PR DESCRIPTION
**Pull request by dcelix**
Added new SNES game: Arkanoid III

### CODE REVIEW

**Comment by nadavbh12** [comment]
I couldn't find this game online. Is it for NES or SNES? What is its official name?

**Comment by hmightypirate** [comment]
The original name was Arkanoid: Doh It Again and it is for the snes.
https://en.wikipedia.org/wiki/Arkanoid:_Doh_It_Again

**Comment by nadavbh12** [comment]
I think it would be better to rename it using its common name. I'm guessing other users, like me, won't be able to find it under the current name.

**Comment by dcelix** [comment]
It's something else we need fix apart from the game rename you pointed out earlier¿

**Comment by nadavbh12** [comment]
Nope, simply forgot about it. Merged!

**Pull request merged**
